FROM node:16.3.0 as deps
ENV NODE_ENV=production NODE_TLS_REJECT_UNAUTHORIZED=0
WORKDIR /app
COPY . .
RUN rm -rf .git \
  && yarn install

FROM node:16.3.0-buster-slim as runner
WORKDIR /app
USER node
COPY --from=deps /app/ ./

CMD ["yarn", "run", "start"]